//
// Licensed to The OpenNMS Group, Inc (TOG) under one or more
// contributor license agreements.  See the LICENSE.md file
// distributed with this work for additional information
// regarding copyright ownership.
//
// TOG licenses this file to You under the GNU Affero General
// Public License Version 3 (the "License") or (at your option)
// any later version.  You may not use this file except in
// compliance with the License.  You may obtain a copy of the
// License at:
//
//      https://www.gnu.org/licenses/agpl-3.0.txt
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied.  See the License for the specific
// language governing permissions and limitations under the
// License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: monitored-services.proto

package bsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceComponent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForeignService string                 `protobuf:"bytes,1,opt,name=foreign_service,json=foreignService,proto3" json:"foreign_service,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Healthy        bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags           []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceComponent) Reset() {
	*x = ServiceComponent{}
	mi := &file_monitored_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceComponent) ProtoMessage() {}

func (x *ServiceComponent) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceComponent.ProtoReflect.Descriptor instead.
func (*ServiceComponent) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceComponent) GetForeignService() string {
	if x != nil {
		return x.ForeignService
	}
	return ""
}

func (x *ServiceComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceComponent) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ServiceComponent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ServiceComponent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type InventoryUpdateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForeignType   string                 `protobuf:"bytes,1,opt,name=foreign_type,json=foreignType,proto3" json:"foreign_type,omitempty"`
	ForeignSource string                 `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3" json:"foreign_source,omitempty"`
	Snapshot      bool                   `protobuf:"varint,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Services      []*ServiceComponent    `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryUpdateList) Reset() {
	*x = InventoryUpdateList{}
	mi := &file_monitored_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdateList) ProtoMessage() {}

func (x *InventoryUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdateList.ProtoReflect.Descriptor instead.
func (*InventoryUpdateList) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryUpdateList) GetForeignType() string {
	if x != nil {
		return x.ForeignType
	}
	return ""
}

func (x *InventoryUpdateList) GetForeignSource() string {
	if x != nil {
		return x.ForeignSource
	}
	return ""
}

func (x *InventoryUpdateList) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *InventoryUpdateList) GetServices() []*ServiceComponent {
	if x != nil {
		return x.Services
	}
	return nil
}

type StateUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForeignService string                 `protobuf:"bytes,1,opt,name=foreign_service,json=foreignService,proto3" json:"foreign_service,omitempty"`
	Healthy        bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_monitored_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{2}
}

func (x *StateUpdate) GetForeignService() string {
	if x != nil {
		return x.ForeignService
	}
	return ""
}

func (x *StateUpdate) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type StateUpdateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForeignType   string                 `protobuf:"bytes,1,opt,name=foreign_type,json=foreignType,proto3" json:"foreign_type,omitempty"`
	ForeignSource string                 `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3" json:"foreign_source,omitempty"`
	Updates       []*StateUpdate         `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdateList) Reset() {
	*x = StateUpdateList{}
	mi := &file_monitored_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdateList) ProtoMessage() {}

func (x *StateUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdateList.ProtoReflect.Descriptor instead.
func (*StateUpdateList) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{3}
}

func (x *StateUpdateList) GetForeignType() string {
	if x != nil {
		return x.ForeignType
	}
	return ""
}

func (x *StateUpdateList) GetForeignSource() string {
	if x != nil {
		return x.ForeignSource
	}
	return ""
}

func (x *StateUpdateList) GetUpdates() []*StateUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type MonitoringInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceType  string                 `protobuf:"bytes,1,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceName  string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringInstance) Reset() {
	*x = MonitoringInstance{}
	mi := &file_monitored_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringInstance) ProtoMessage() {}

func (x *MonitoringInstance) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringInstance.ProtoReflect.Descriptor instead.
func (*MonitoringInstance) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{4}
}

func (x *MonitoringInstance) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *MonitoringInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MonitoringInstance) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type HeartBeat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MonitoringInstance *MonitoringInstance    `protobuf:"bytes,1,opt,name=monitoring_instance,json=monitoringInstance,proto3" json:"monitoring_instance,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp          uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	mi := &file_monitored_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_monitored_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_monitored_services_proto_rawDescGZIP(), []int{5}
}

func (x *HeartBeat) GetMonitoringInstance() *MonitoringInstance {
	if x != nil {
		return x.MonitoringInstance
	}
	return nil
}

func (x *HeartBeat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartBeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_monitored_services_proto protoreflect.FileDescriptor

const file_monitored_services_proto_rawDesc = "" +
	"\n" +
	"\x18monitored-services.proto\x12&org.opennms.plugin.grpc.proto.services\x1a\x1bgoogle/protobuf/empty.proto\"\xa6\x02\n" +
	"\x10ServiceComponent\x12'\n" +
	"\x0fforeign_service\x18\x01 \x01(\tR\x0eforeignService\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12h\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2H.org.opennms.plugin.grpc.proto.services.ServiceComponent.AttributesEntryR\n" +
	"attributes\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x13InventoryUpdateList\x12!\n" +
	"\fforeign_type\x18\x01 \x01(\tR\vforeignType\x12%\n" +
	"\x0eforeign_source\x18\x02 \x01(\tR\rforeignSource\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\bR\bsnapshot\x12T\n" +
	"\bservices\x18\x04 \x03(\v28.org.opennms.plugin.grpc.proto.services.ServiceComponentR\bservices\"P\n" +
	"\vStateUpdate\x12'\n" +
	"\x0fforeign_service\x18\x01 \x01(\tR\x0eforeignService\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"\xaa\x01\n" +
	"\x0fStateUpdateList\x12!\n" +
	"\fforeign_type\x18\x01 \x01(\tR\vforeignType\x12%\n" +
	"\x0eforeign_source\x18\x02 \x01(\tR\rforeignSource\x12M\n" +
	"\aupdates\x18\x03 \x03(\v23.org.opennms.plugin.grpc.proto.services.StateUpdateR\aupdates\"\x7f\n" +
	"\x12MonitoringInstance\x12#\n" +
	"\rinstance_type\x18\x01 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\"\xb0\x01\n" +
	"\tHeartBeat\x12k\n" +
	"\x13monitoring_instance\x18\x01 \x01(\v2:.org.opennms.plugin.grpc.proto.services.MonitoringInstanceR\x12monitoringInstance\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp2\xc5\x02\n" +
	"\vServiceSync\x12l\n" +
	"\x0fInventoryUpdate\x12;.org.opennms.plugin.grpc.proto.services.InventoryUpdateList\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01\x12d\n" +
	"\vStateUpdate\x127.org.opennms.plugin.grpc.proto.services.StateUpdateList\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01\x12b\n" +
	"\x0fHeartBeatUpdate\x121.org.opennms.plugin.grpc.proto.services.HeartBeat\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01B*\n" +
	"&org.opennms.plugin.grpc.proto.servicesP\x01b\x06proto3"

var (
	file_monitored_services_proto_rawDescOnce sync.Once
	file_monitored_services_proto_rawDescData []byte
)

func file_monitored_services_proto_rawDescGZIP() []byte {
	file_monitored_services_proto_rawDescOnce.Do(func() {
		file_monitored_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitored_services_proto_rawDesc), len(file_monitored_services_proto_rawDesc)))
	})
	return file_monitored_services_proto_rawDescData
}

var file_monitored_services_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_monitored_services_proto_goTypes = []any{
	(*ServiceComponent)(nil),    // 0: org.opennms.plugin.grpc.proto.services.ServiceComponent
	(*InventoryUpdateList)(nil), // 1: org.opennms.plugin.grpc.proto.services.InventoryUpdateList
	(*StateUpdate)(nil),         // 2: org.opennms.plugin.grpc.proto.services.StateUpdate
	(*StateUpdateList)(nil),     // 3: org.opennms.plugin.grpc.proto.services.StateUpdateList
	(*MonitoringInstance)(nil),  // 4: org.opennms.plugin.grpc.proto.services.MonitoringInstance
	(*HeartBeat)(nil),           // 5: org.opennms.plugin.grpc.proto.services.HeartBeat
	nil,                         // 6: org.opennms.plugin.grpc.proto.services.ServiceComponent.AttributesEntry
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_monitored_services_proto_depIdxs = []int32{
	6, // 0: org.opennms.plugin.grpc.proto.services.ServiceComponent.attributes:type_name -> org.opennms.plugin.grpc.proto.services.ServiceComponent.AttributesEntry
	0, // 1: org.opennms.plugin.grpc.proto.services.InventoryUpdateList.services:type_name -> org.opennms.plugin.grpc.proto.services.ServiceComponent
	2, // 2: org.opennms.plugin.grpc.proto.services.StateUpdateList.updates:type_name -> org.opennms.plugin.grpc.proto.services.StateUpdate
	4, // 3: org.opennms.plugin.grpc.proto.services.HeartBeat.monitoring_instance:type_name -> org.opennms.plugin.grpc.proto.services.MonitoringInstance
	1, // 4: org.opennms.plugin.grpc.proto.services.ServiceSync.InventoryUpdate:input_type -> org.opennms.plugin.grpc.proto.services.InventoryUpdateList
	3, // 5: org.opennms.plugin.grpc.proto.services.ServiceSync.StateUpdate:input_type -> org.opennms.plugin.grpc.proto.services.StateUpdateList
	5, // 6: org.opennms.plugin.grpc.proto.services.ServiceSync.HeartBeatUpdate:input_type -> org.opennms.plugin.grpc.proto.services.HeartBeat
	7, // 7: org.opennms.plugin.grpc.proto.services.ServiceSync.InventoryUpdate:output_type -> google.protobuf.Empty
	7, // 8: org.opennms.plugin.grpc.proto.services.ServiceSync.StateUpdate:output_type -> google.protobuf.Empty
	7, // 9: org.opennms.plugin.grpc.proto.services.ServiceSync.HeartBeatUpdate:output_type -> google.protobuf.Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_monitored_services_proto_init() }
func file_monitored_services_proto_init() {
	if File_monitored_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitored_services_proto_rawDesc), len(file_monitored_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitored_services_proto_goTypes,
		DependencyIndexes: file_monitored_services_proto_depIdxs,
		MessageInfos:      file_monitored_services_proto_msgTypes,
	}.Build()
	File_monitored_services_proto = out.File
	file_monitored_services_proto_goTypes = nil
	file_monitored_services_proto_depIdxs = nil
}
