project_name: onms-grpc-receiver

version: 2

builds:
  - id: onms-grpc-receiver
    binary: onms-grpc-receiver
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    main: ./cmd/onms-grpc-receiver
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
    ldflags:
      - -s -w -X github.com/andrewheberle/onms-grpc-receiver/pkg/cmd.Version={{ .Version }} -X main.Date={{ .CommitDate }}

gomod:
  proxy: true

changelog:
  use: github-native

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  make_latest: true
  replace_existing_artifacts: true
  prerelease: auto

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

sboms:
  - artifacts: binary
    disable: false

snapshot:
  version_template: "{{ incpatch .Version }}"

dockers_v2:
  - images:
      - "ghcr.io/andrewheberle/{{ .ProjectName }}"
    ids:
      - "{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    sbom: "{{ not .IsSnapshot }}"
    disable: false
    platforms:
      - linux/amd64
    labels:
      "org.opencontainers.image.description": "An OpenNMS gRPC receiver"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    annotations:
      "index:org.opencontainers.image.description": "An OpenNMS gRPC receiver"

docker_digest:
  name_template: "digests.txt"

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"