//
// Licensed to The OpenNMS Group, Inc (TOG) under one or more
// contributor license agreements.  See the LICENSE.md file
// distributed with this work for additional information
// regarding copyright ownership.
//
// TOG licenses this file to You under the GNU Affero General
// Public License Version 3 (the "License") or (at your option)
// any later version.  You may not use this file except in
// compliance with the License.  You may obtain a copy of the
// License at:
//
//      https://www.gnu.org/licenses/agpl-3.0.txt
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied.  See the License for the specific
// language governing permissions and limitations under the
// License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spog.proto

package spog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_INDETERMINATE Severity = 0
	Severity_CLEARED       Severity = 1
	Severity_NORMAL        Severity = 2
	Severity_WARNING       Severity = 3
	Severity_MINOR         Severity = 4
	Severity_MAJOR         Severity = 5
	Severity_CRITICAL      Severity = 6
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INDETERMINATE",
		1: "CLEARED",
		2: "NORMAL",
		3: "WARNING",
		4: "MINOR",
		5: "MAJOR",
		6: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INDETERMINATE": 0,
		"CLEARED":       1,
		"NORMAL":        2,
		"WARNING":       3,
		"MINOR":         4,
		"MAJOR":         5,
		"CRITICAL":      6,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_spog_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_spog_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Alarm_Type int32

const (
	Alarm_PROBLEM_WITH_CLEAR    Alarm_Type = 0
	Alarm_CLEAR                 Alarm_Type = 1
	Alarm_PROBLEM_WITHOUT_CLEAR Alarm_Type = 2
)

// Enum value maps for Alarm_Type.
var (
	Alarm_Type_name = map[int32]string{
		0: "PROBLEM_WITH_CLEAR",
		1: "CLEAR",
		2: "PROBLEM_WITHOUT_CLEAR",
	}
	Alarm_Type_value = map[string]int32{
		"PROBLEM_WITH_CLEAR":    0,
		"CLEAR":                 1,
		"PROBLEM_WITHOUT_CLEAR": 2,
	}
)

func (x Alarm_Type) Enum() *Alarm_Type {
	p := new(Alarm_Type)
	*p = x
	return p
}

func (x Alarm_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alarm_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_spog_proto_enumTypes[1].Descriptor()
}

func (Alarm_Type) Type() protoreflect.EnumType {
	return &file_spog_proto_enumTypes[1]
}

func (x Alarm_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NodeCriteria struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_ForeignSource string                 `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3"`
	xxx_hidden_ForeignId     string                 `protobuf:"bytes,3,opt,name=foreign_id,json=foreignId,proto3"`
	xxx_hidden_NodeLabel     string                 `protobuf:"bytes,4,opt,name=node_label,json=nodeLabel,proto3"`
	xxx_hidden_Location      string                 `protobuf:"bytes,5,opt,name=location,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NodeCriteria) Reset() {
	*x = NodeCriteria{}
	mi := &file_spog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCriteria) ProtoMessage() {}

func (x *NodeCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NodeCriteria) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *NodeCriteria) GetForeignSource() string {
	if x != nil {
		return x.xxx_hidden_ForeignSource
	}
	return ""
}

func (x *NodeCriteria) GetForeignId() string {
	if x != nil {
		return x.xxx_hidden_ForeignId
	}
	return ""
}

func (x *NodeCriteria) GetNodeLabel() string {
	if x != nil {
		return x.xxx_hidden_NodeLabel
	}
	return ""
}

func (x *NodeCriteria) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *NodeCriteria) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *NodeCriteria) SetForeignSource(v string) {
	x.xxx_hidden_ForeignSource = v
}

func (x *NodeCriteria) SetForeignId(v string) {
	x.xxx_hidden_ForeignId = v
}

func (x *NodeCriteria) SetNodeLabel(v string) {
	x.xxx_hidden_NodeLabel = v
}

func (x *NodeCriteria) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

type NodeCriteria_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            uint64
	ForeignSource string
	ForeignId     string
	NodeLabel     string
	Location      string
}

func (b0 NodeCriteria_builder) Build() *NodeCriteria {
	m0 := &NodeCriteria{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ForeignSource = b.ForeignSource
	x.xxx_hidden_ForeignId = b.ForeignId
	x.xxx_hidden_NodeLabel = b.NodeLabel
	x.xxx_hidden_Location = b.Location
	return m0
}

type IpInterface struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_IpAddress   string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3"`
	xxx_hidden_PrimaryType string                 `protobuf:"bytes,3,opt,name=primary_type,json=primaryType,proto3"`
	xxx_hidden_Service     []string               `protobuf:"bytes,4,rep,name=service,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IpInterface) Reset() {
	*x = IpInterface{}
	mi := &file_spog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpInterface) ProtoMessage() {}

func (x *IpInterface) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IpInterface) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *IpInterface) GetIpAddress() string {
	if x != nil {
		return x.xxx_hidden_IpAddress
	}
	return ""
}

func (x *IpInterface) GetPrimaryType() string {
	if x != nil {
		return x.xxx_hidden_PrimaryType
	}
	return ""
}

func (x *IpInterface) GetService() []string {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return nil
}

func (x *IpInterface) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *IpInterface) SetIpAddress(v string) {
	x.xxx_hidden_IpAddress = v
}

func (x *IpInterface) SetPrimaryType(v string) {
	x.xxx_hidden_PrimaryType = v
}

func (x *IpInterface) SetService(v []string) {
	x.xxx_hidden_Service = v
}

type IpInterface_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          uint64
	IpAddress   string
	PrimaryType string
	Service     []string
}

func (b0 IpInterface_builder) Build() *IpInterface {
	m0 := &IpInterface{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_IpAddress = b.IpAddress
	x.xxx_hidden_PrimaryType = b.PrimaryType
	x.xxx_hidden_Service = b.Service
	return m0
}

type SnmpInterface struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_IfIndex       uint32                 `protobuf:"varint,2,opt,name=if_index,json=ifIndex,proto3"`
	xxx_hidden_IfDescr       string                 `protobuf:"bytes,3,opt,name=if_descr,json=ifDescr,proto3"`
	xxx_hidden_IfType        uint32                 `protobuf:"varint,4,opt,name=if_type,json=ifType,proto3"`
	xxx_hidden_IfName        string                 `protobuf:"bytes,5,opt,name=if_name,json=ifName,proto3"`
	xxx_hidden_IfSpeed       uint64                 `protobuf:"varint,6,opt,name=if_speed,json=ifSpeed,proto3"`
	xxx_hidden_IfPhysAddress string                 `protobuf:"bytes,7,opt,name=if_phys_address,json=ifPhysAddress,proto3"`
	xxx_hidden_IfAdminStatus uint32                 `protobuf:"varint,8,opt,name=if_admin_status,json=ifAdminStatus,proto3"`
	xxx_hidden_IfOperStatus  uint32                 `protobuf:"varint,9,opt,name=if_oper_status,json=ifOperStatus,proto3"`
	xxx_hidden_IfAlias       string                 `protobuf:"bytes,10,opt,name=if_alias,json=ifAlias,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SnmpInterface) Reset() {
	*x = SnmpInterface{}
	mi := &file_spog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnmpInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpInterface) ProtoMessage() {}

func (x *SnmpInterface) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SnmpInterface) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *SnmpInterface) GetIfIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_IfIndex
	}
	return 0
}

func (x *SnmpInterface) GetIfDescr() string {
	if x != nil {
		return x.xxx_hidden_IfDescr
	}
	return ""
}

func (x *SnmpInterface) GetIfType() uint32 {
	if x != nil {
		return x.xxx_hidden_IfType
	}
	return 0
}

func (x *SnmpInterface) GetIfName() string {
	if x != nil {
		return x.xxx_hidden_IfName
	}
	return ""
}

func (x *SnmpInterface) GetIfSpeed() uint64 {
	if x != nil {
		return x.xxx_hidden_IfSpeed
	}
	return 0
}

func (x *SnmpInterface) GetIfPhysAddress() string {
	if x != nil {
		return x.xxx_hidden_IfPhysAddress
	}
	return ""
}

func (x *SnmpInterface) GetIfAdminStatus() uint32 {
	if x != nil {
		return x.xxx_hidden_IfAdminStatus
	}
	return 0
}

func (x *SnmpInterface) GetIfOperStatus() uint32 {
	if x != nil {
		return x.xxx_hidden_IfOperStatus
	}
	return 0
}

func (x *SnmpInterface) GetIfAlias() string {
	if x != nil {
		return x.xxx_hidden_IfAlias
	}
	return ""
}

func (x *SnmpInterface) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *SnmpInterface) SetIfIndex(v uint32) {
	x.xxx_hidden_IfIndex = v
}

func (x *SnmpInterface) SetIfDescr(v string) {
	x.xxx_hidden_IfDescr = v
}

func (x *SnmpInterface) SetIfType(v uint32) {
	x.xxx_hidden_IfType = v
}

func (x *SnmpInterface) SetIfName(v string) {
	x.xxx_hidden_IfName = v
}

func (x *SnmpInterface) SetIfSpeed(v uint64) {
	x.xxx_hidden_IfSpeed = v
}

func (x *SnmpInterface) SetIfPhysAddress(v string) {
	x.xxx_hidden_IfPhysAddress = v
}

func (x *SnmpInterface) SetIfAdminStatus(v uint32) {
	x.xxx_hidden_IfAdminStatus = v
}

func (x *SnmpInterface) SetIfOperStatus(v uint32) {
	x.xxx_hidden_IfOperStatus = v
}

func (x *SnmpInterface) SetIfAlias(v string) {
	x.xxx_hidden_IfAlias = v
}

type SnmpInterface_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            uint64
	IfIndex       uint32
	IfDescr       string
	IfType        uint32
	IfName        string
	IfSpeed       uint64
	IfPhysAddress string
	IfAdminStatus uint32
	IfOperStatus  uint32
	IfAlias       string
}

func (b0 SnmpInterface_builder) Build() *SnmpInterface {
	m0 := &SnmpInterface{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_IfIndex = b.IfIndex
	x.xxx_hidden_IfDescr = b.IfDescr
	x.xxx_hidden_IfType = b.IfType
	x.xxx_hidden_IfName = b.IfName
	x.xxx_hidden_IfSpeed = b.IfSpeed
	x.xxx_hidden_IfPhysAddress = b.IfPhysAddress
	x.xxx_hidden_IfAdminStatus = b.IfAdminStatus
	x.xxx_hidden_IfOperStatus = b.IfOperStatus
	x.xxx_hidden_IfAlias = b.IfAlias
	return m0
}

type Node struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_ForeignSource  string                 `protobuf:"bytes,2,opt,name=foreign_source,json=foreignSource,proto3"`
	xxx_hidden_ForeignId      string                 `protobuf:"bytes,3,opt,name=foreign_id,json=foreignId,proto3"`
	xxx_hidden_Location       string                 `protobuf:"bytes,4,opt,name=location,proto3"`
	xxx_hidden_Category       []string               `protobuf:"bytes,5,rep,name=category,proto3"`
	xxx_hidden_Label          string                 `protobuf:"bytes,6,opt,name=label,proto3"`
	xxx_hidden_CreateTime     uint64                 `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3"`
	xxx_hidden_SysContact     string                 `protobuf:"bytes,8,opt,name=sys_contact,json=sysContact,proto3"`
	xxx_hidden_SysDescription string                 `protobuf:"bytes,9,opt,name=sys_description,json=sysDescription,proto3"`
	xxx_hidden_SysObjectId    string                 `protobuf:"bytes,10,opt,name=sys_object_id,json=sysObjectId,proto3"`
	xxx_hidden_SysName        string                 `protobuf:"bytes,11,opt,name=sys_name,json=sysName,proto3"`
	xxx_hidden_IpInterface    *[]*IpInterface        `protobuf:"bytes,12,rep,name=ip_interface,json=ipInterface,proto3"`
	xxx_hidden_SnmpInterface  *[]*SnmpInterface      `protobuf:"bytes,13,rep,name=snmp_interface,json=snmpInterface,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_spog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Node) GetForeignSource() string {
	if x != nil {
		return x.xxx_hidden_ForeignSource
	}
	return ""
}

func (x *Node) GetForeignId() string {
	if x != nil {
		return x.xxx_hidden_ForeignId
	}
	return ""
}

func (x *Node) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *Node) GetCategory() []string {
	if x != nil {
		return x.xxx_hidden_Category
	}
	return nil
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Node) GetCreateTime() uint64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *Node) GetSysContact() string {
	if x != nil {
		return x.xxx_hidden_SysContact
	}
	return ""
}

func (x *Node) GetSysDescription() string {
	if x != nil {
		return x.xxx_hidden_SysDescription
	}
	return ""
}

func (x *Node) GetSysObjectId() string {
	if x != nil {
		return x.xxx_hidden_SysObjectId
	}
	return ""
}

func (x *Node) GetSysName() string {
	if x != nil {
		return x.xxx_hidden_SysName
	}
	return ""
}

func (x *Node) GetIpInterface() []*IpInterface {
	if x != nil {
		if x.xxx_hidden_IpInterface != nil {
			return *x.xxx_hidden_IpInterface
		}
	}
	return nil
}

func (x *Node) GetSnmpInterface() []*SnmpInterface {
	if x != nil {
		if x.xxx_hidden_SnmpInterface != nil {
			return *x.xxx_hidden_SnmpInterface
		}
	}
	return nil
}

func (x *Node) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *Node) SetForeignSource(v string) {
	x.xxx_hidden_ForeignSource = v
}

func (x *Node) SetForeignId(v string) {
	x.xxx_hidden_ForeignId = v
}

func (x *Node) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

func (x *Node) SetCategory(v []string) {
	x.xxx_hidden_Category = v
}

func (x *Node) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Node) SetCreateTime(v uint64) {
	x.xxx_hidden_CreateTime = v
}

func (x *Node) SetSysContact(v string) {
	x.xxx_hidden_SysContact = v
}

func (x *Node) SetSysDescription(v string) {
	x.xxx_hidden_SysDescription = v
}

func (x *Node) SetSysObjectId(v string) {
	x.xxx_hidden_SysObjectId = v
}

func (x *Node) SetSysName(v string) {
	x.xxx_hidden_SysName = v
}

func (x *Node) SetIpInterface(v []*IpInterface) {
	x.xxx_hidden_IpInterface = &v
}

func (x *Node) SetSnmpInterface(v []*SnmpInterface) {
	x.xxx_hidden_SnmpInterface = &v
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             uint64
	ForeignSource  string
	ForeignId      string
	Location       string
	Category       []string
	Label          string
	CreateTime     uint64
	SysContact     string
	SysDescription string
	SysObjectId    string
	SysName        string
	IpInterface    []*IpInterface
	SnmpInterface  []*SnmpInterface
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ForeignSource = b.ForeignSource
	x.xxx_hidden_ForeignId = b.ForeignId
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_Category = b.Category
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_CreateTime = b.CreateTime
	x.xxx_hidden_SysContact = b.SysContact
	x.xxx_hidden_SysDescription = b.SysDescription
	x.xxx_hidden_SysObjectId = b.SysObjectId
	x.xxx_hidden_SysName = b.SysName
	x.xxx_hidden_IpInterface = &b.IpInterface
	x.xxx_hidden_SnmpInterface = &b.SnmpInterface
	return m0
}

type Alarm struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                    uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Uei                   string                 `protobuf:"bytes,2,opt,name=uei,proto3"`
	xxx_hidden_NodeCriteria          *NodeCriteria          `protobuf:"bytes,3,opt,name=node_criteria,json=nodeCriteria,proto3"`
	xxx_hidden_IpAddress             string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3"`
	xxx_hidden_ServiceName           string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3"`
	xxx_hidden_ReductionKey          string                 `protobuf:"bytes,6,opt,name=reduction_key,json=reductionKey,proto3"`
	xxx_hidden_Type                  uint32                 `protobuf:"varint,7,opt,name=type,proto3"`
	xxx_hidden_Count                 uint64                 `protobuf:"varint,8,opt,name=count,proto3"`
	xxx_hidden_Severity              uint32                 `protobuf:"varint,9,opt,name=severity,proto3"`
	xxx_hidden_FirstEventTime        uint64                 `protobuf:"varint,10,opt,name=first_event_time,json=firstEventTime,proto3"`
	xxx_hidden_Description           string                 `protobuf:"bytes,11,opt,name=description,proto3"`
	xxx_hidden_LogMessage            string                 `protobuf:"bytes,12,opt,name=log_message,json=logMessage,proto3"`
	xxx_hidden_AckUser               string                 `protobuf:"bytes,13,opt,name=ack_user,json=ackUser,proto3"`
	xxx_hidden_AckTime               uint64                 `protobuf:"varint,14,opt,name=ack_time,json=ackTime,proto3"`
	xxx_hidden_LastEventTime         uint64                 `protobuf:"varint,16,opt,name=last_event_time,json=lastEventTime,proto3"`
	xxx_hidden_IfIndex               uint32                 `protobuf:"varint,17,opt,name=if_index,json=ifIndex,proto3"`
	xxx_hidden_OperatorInstructions  string                 `protobuf:"bytes,18,opt,name=operator_instructions,json=operatorInstructions,proto3"`
	xxx_hidden_ClearKey              string                 `protobuf:"bytes,19,opt,name=clear_key,json=clearKey,proto3"`
	xxx_hidden_ManagedObjectInstance string                 `protobuf:"bytes,20,opt,name=managed_object_instance,json=managedObjectInstance,proto3"`
	xxx_hidden_ManagedObjectType     string                 `protobuf:"bytes,21,opt,name=managed_object_type,json=managedObjectType,proto3"`
	xxx_hidden_RelatedAlarm          *[]*Alarm              `protobuf:"bytes,22,rep,name=relatedAlarm,proto3"`
	xxx_hidden_LastUpdateTime        uint64                 `protobuf:"varint,25,opt,name=last_update_time,json=lastUpdateTime,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_spog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Alarm) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Alarm) GetUei() string {
	if x != nil {
		return x.xxx_hidden_Uei
	}
	return ""
}

func (x *Alarm) GetNodeCriteria() *NodeCriteria {
	if x != nil {
		return x.xxx_hidden_NodeCriteria
	}
	return nil
}

func (x *Alarm) GetIpAddress() string {
	if x != nil {
		return x.xxx_hidden_IpAddress
	}
	return ""
}

func (x *Alarm) GetServiceName() string {
	if x != nil {
		return x.xxx_hidden_ServiceName
	}
	return ""
}

func (x *Alarm) GetReductionKey() string {
	if x != nil {
		return x.xxx_hidden_ReductionKey
	}
	return ""
}

func (x *Alarm) GetType() uint32 {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return 0
}

func (x *Alarm) GetCount() uint64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *Alarm) GetSeverity() uint32 {
	if x != nil {
		return x.xxx_hidden_Severity
	}
	return 0
}

func (x *Alarm) GetFirstEventTime() uint64 {
	if x != nil {
		return x.xxx_hidden_FirstEventTime
	}
	return 0
}

func (x *Alarm) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Alarm) GetLogMessage() string {
	if x != nil {
		return x.xxx_hidden_LogMessage
	}
	return ""
}

func (x *Alarm) GetAckUser() string {
	if x != nil {
		return x.xxx_hidden_AckUser
	}
	return ""
}

func (x *Alarm) GetAckTime() uint64 {
	if x != nil {
		return x.xxx_hidden_AckTime
	}
	return 0
}

func (x *Alarm) GetLastEventTime() uint64 {
	if x != nil {
		return x.xxx_hidden_LastEventTime
	}
	return 0
}

func (x *Alarm) GetIfIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_IfIndex
	}
	return 0
}

func (x *Alarm) GetOperatorInstructions() string {
	if x != nil {
		return x.xxx_hidden_OperatorInstructions
	}
	return ""
}

func (x *Alarm) GetClearKey() string {
	if x != nil {
		return x.xxx_hidden_ClearKey
	}
	return ""
}

func (x *Alarm) GetManagedObjectInstance() string {
	if x != nil {
		return x.xxx_hidden_ManagedObjectInstance
	}
	return ""
}

func (x *Alarm) GetManagedObjectType() string {
	if x != nil {
		return x.xxx_hidden_ManagedObjectType
	}
	return ""
}

func (x *Alarm) GetRelatedAlarm() []*Alarm {
	if x != nil {
		if x.xxx_hidden_RelatedAlarm != nil {
			return *x.xxx_hidden_RelatedAlarm
		}
	}
	return nil
}

func (x *Alarm) GetLastUpdateTime() uint64 {
	if x != nil {
		return x.xxx_hidden_LastUpdateTime
	}
	return 0
}

func (x *Alarm) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *Alarm) SetUei(v string) {
	x.xxx_hidden_Uei = v
}

func (x *Alarm) SetNodeCriteria(v *NodeCriteria) {
	x.xxx_hidden_NodeCriteria = v
}

func (x *Alarm) SetIpAddress(v string) {
	x.xxx_hidden_IpAddress = v
}

func (x *Alarm) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = v
}

func (x *Alarm) SetReductionKey(v string) {
	x.xxx_hidden_ReductionKey = v
}

func (x *Alarm) SetType(v uint32) {
	x.xxx_hidden_Type = v
}

func (x *Alarm) SetCount(v uint64) {
	x.xxx_hidden_Count = v
}

func (x *Alarm) SetSeverity(v uint32) {
	x.xxx_hidden_Severity = v
}

func (x *Alarm) SetFirstEventTime(v uint64) {
	x.xxx_hidden_FirstEventTime = v
}

func (x *Alarm) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Alarm) SetLogMessage(v string) {
	x.xxx_hidden_LogMessage = v
}

func (x *Alarm) SetAckUser(v string) {
	x.xxx_hidden_AckUser = v
}

func (x *Alarm) SetAckTime(v uint64) {
	x.xxx_hidden_AckTime = v
}

func (x *Alarm) SetLastEventTime(v uint64) {
	x.xxx_hidden_LastEventTime = v
}

func (x *Alarm) SetIfIndex(v uint32) {
	x.xxx_hidden_IfIndex = v
}

func (x *Alarm) SetOperatorInstructions(v string) {
	x.xxx_hidden_OperatorInstructions = v
}

func (x *Alarm) SetClearKey(v string) {
	x.xxx_hidden_ClearKey = v
}

func (x *Alarm) SetManagedObjectInstance(v string) {
	x.xxx_hidden_ManagedObjectInstance = v
}

func (x *Alarm) SetManagedObjectType(v string) {
	x.xxx_hidden_ManagedObjectType = v
}

func (x *Alarm) SetRelatedAlarm(v []*Alarm) {
	x.xxx_hidden_RelatedAlarm = &v
}

func (x *Alarm) SetLastUpdateTime(v uint64) {
	x.xxx_hidden_LastUpdateTime = v
}

func (x *Alarm) HasNodeCriteria() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NodeCriteria != nil
}

func (x *Alarm) ClearNodeCriteria() {
	x.xxx_hidden_NodeCriteria = nil
}

type Alarm_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                    uint64
	Uei                   string
	NodeCriteria          *NodeCriteria
	IpAddress             string
	ServiceName           string
	ReductionKey          string
	Type                  uint32
	Count                 uint64
	Severity              uint32
	FirstEventTime        uint64
	Description           string
	LogMessage            string
	AckUser               string
	AckTime               uint64
	LastEventTime         uint64
	IfIndex               uint32
	OperatorInstructions  string
	ClearKey              string
	ManagedObjectInstance string
	ManagedObjectType     string
	RelatedAlarm          []*Alarm
	LastUpdateTime        uint64
}

func (b0 Alarm_builder) Build() *Alarm {
	m0 := &Alarm{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Uei = b.Uei
	x.xxx_hidden_NodeCriteria = b.NodeCriteria
	x.xxx_hidden_IpAddress = b.IpAddress
	x.xxx_hidden_ServiceName = b.ServiceName
	x.xxx_hidden_ReductionKey = b.ReductionKey
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_Severity = b.Severity
	x.xxx_hidden_FirstEventTime = b.FirstEventTime
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_LogMessage = b.LogMessage
	x.xxx_hidden_AckUser = b.AckUser
	x.xxx_hidden_AckTime = b.AckTime
	x.xxx_hidden_LastEventTime = b.LastEventTime
	x.xxx_hidden_IfIndex = b.IfIndex
	x.xxx_hidden_OperatorInstructions = b.OperatorInstructions
	x.xxx_hidden_ClearKey = b.ClearKey
	x.xxx_hidden_ManagedObjectInstance = b.ManagedObjectInstance
	x.xxx_hidden_ManagedObjectType = b.ManagedObjectType
	x.xxx_hidden_RelatedAlarm = &b.RelatedAlarm
	x.xxx_hidden_LastUpdateTime = b.LastUpdateTime
	return m0
}

type EventParameter struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	xxx_hidden_Type  string                 `protobuf:"bytes,3,opt,name=type,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventParameter) Reset() {
	*x = EventParameter{}
	mi := &file_spog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventParameter) ProtoMessage() {}

func (x *EventParameter) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventParameter) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *EventParameter) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *EventParameter) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *EventParameter) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *EventParameter) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *EventParameter) SetType(v string) {
	x.xxx_hidden_Type = v
}

type EventParameter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  string
	Value string
	Type  string
}

func (b0 EventParameter_builder) Build() *EventParameter {
	m0 := &EventParameter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Type = b.Type
	return m0
}

type SnmpInfo struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Version   string                 `protobuf:"bytes,2,opt,name=version,proto3"`
	xxx_hidden_Specific  uint32                 `protobuf:"varint,3,opt,name=specific,proto3"`
	xxx_hidden_Generic   uint32                 `protobuf:"varint,4,opt,name=generic,proto3"`
	xxx_hidden_Community string                 `protobuf:"bytes,5,opt,name=community,proto3"`
	xxx_hidden_TrapOid   string                 `protobuf:"bytes,6,opt,name=trap_oid,json=trapOid,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SnmpInfo) Reset() {
	*x = SnmpInfo{}
	mi := &file_spog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnmpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpInfo) ProtoMessage() {}

func (x *SnmpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SnmpInfo) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SnmpInfo) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *SnmpInfo) GetSpecific() uint32 {
	if x != nil {
		return x.xxx_hidden_Specific
	}
	return 0
}

func (x *SnmpInfo) GetGeneric() uint32 {
	if x != nil {
		return x.xxx_hidden_Generic
	}
	return 0
}

func (x *SnmpInfo) GetCommunity() string {
	if x != nil {
		return x.xxx_hidden_Community
	}
	return ""
}

func (x *SnmpInfo) GetTrapOid() string {
	if x != nil {
		return x.xxx_hidden_TrapOid
	}
	return ""
}

func (x *SnmpInfo) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SnmpInfo) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *SnmpInfo) SetSpecific(v uint32) {
	x.xxx_hidden_Specific = v
}

func (x *SnmpInfo) SetGeneric(v uint32) {
	x.xxx_hidden_Generic = v
}

func (x *SnmpInfo) SetCommunity(v string) {
	x.xxx_hidden_Community = v
}

func (x *SnmpInfo) SetTrapOid(v string) {
	x.xxx_hidden_TrapOid = v
}

type SnmpInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        string
	Version   string
	Specific  uint32
	Generic   uint32
	Community string
	TrapOid   string
}

func (b0 SnmpInfo_builder) Build() *SnmpInfo {
	m0 := &SnmpInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Specific = b.Specific
	x.xxx_hidden_Generic = b.Generic
	x.xxx_hidden_Community = b.Community
	x.xxx_hidden_TrapOid = b.TrapOid
	return m0
}

type Event struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Uei         string                 `protobuf:"bytes,2,opt,name=uei,proto3"`
	xxx_hidden_Time        uint64                 `protobuf:"varint,3,opt,name=time,proto3"`
	xxx_hidden_Source      string                 `protobuf:"bytes,4,opt,name=source,proto3"`
	xxx_hidden_Parameter   *[]*EventParameter     `protobuf:"bytes,5,rep,name=parameter,proto3"`
	xxx_hidden_CreateTime  uint64                 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,7,opt,name=description,proto3"`
	xxx_hidden_LogMessage  string                 `protobuf:"bytes,8,opt,name=log_message,json=logMessage,proto3"`
	xxx_hidden_Severity    Severity               `protobuf:"varint,9,opt,name=severity,proto3,enum=org.opennms.plugin.grpc.proto.spog.Severity"`
	xxx_hidden_IpAddress   string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3"`
	xxx_hidden_DistPoller  string                 `protobuf:"bytes,11,opt,name=dist_poller,json=distPoller,proto3"`
	xxx_hidden_SnmpInfo    *SnmpInfo              `protobuf:"bytes,12,opt,name=snmpInfo,proto3"`
	xxx_hidden_NodeId      uint64                 `protobuf:"varint,13,opt,name=node_id,json=nodeId,proto3"`
	xxx_hidden_Label       string                 `protobuf:"bytes,14,opt,name=label,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_spog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Event) GetUei() string {
	if x != nil {
		return x.xxx_hidden_Uei
	}
	return ""
}

func (x *Event) GetTime() uint64 {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return 0
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *Event) GetParameter() []*EventParameter {
	if x != nil {
		if x.xxx_hidden_Parameter != nil {
			return *x.xxx_hidden_Parameter
		}
	}
	return nil
}

func (x *Event) GetCreateTime() uint64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Event) GetLogMessage() string {
	if x != nil {
		return x.xxx_hidden_LogMessage
	}
	return ""
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.xxx_hidden_Severity
	}
	return Severity_INDETERMINATE
}

func (x *Event) GetIpAddress() string {
	if x != nil {
		return x.xxx_hidden_IpAddress
	}
	return ""
}

func (x *Event) GetDistPoller() string {
	if x != nil {
		return x.xxx_hidden_DistPoller
	}
	return ""
}

func (x *Event) GetSnmpInfo() *SnmpInfo {
	if x != nil {
		return x.xxx_hidden_SnmpInfo
	}
	return nil
}

func (x *Event) GetNodeId() uint64 {
	if x != nil {
		return x.xxx_hidden_NodeId
	}
	return 0
}

func (x *Event) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Event) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *Event) SetUei(v string) {
	x.xxx_hidden_Uei = v
}

func (x *Event) SetTime(v uint64) {
	x.xxx_hidden_Time = v
}

func (x *Event) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *Event) SetParameter(v []*EventParameter) {
	x.xxx_hidden_Parameter = &v
}

func (x *Event) SetCreateTime(v uint64) {
	x.xxx_hidden_CreateTime = v
}

func (x *Event) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Event) SetLogMessage(v string) {
	x.xxx_hidden_LogMessage = v
}

func (x *Event) SetSeverity(v Severity) {
	x.xxx_hidden_Severity = v
}

func (x *Event) SetIpAddress(v string) {
	x.xxx_hidden_IpAddress = v
}

func (x *Event) SetDistPoller(v string) {
	x.xxx_hidden_DistPoller = v
}

func (x *Event) SetSnmpInfo(v *SnmpInfo) {
	x.xxx_hidden_SnmpInfo = v
}

func (x *Event) SetNodeId(v uint64) {
	x.xxx_hidden_NodeId = v
}

func (x *Event) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Event) HasSnmpInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SnmpInfo != nil
}

func (x *Event) ClearSnmpInfo() {
	x.xxx_hidden_SnmpInfo = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          uint64
	Uei         string
	Time        uint64
	Source      string
	Parameter   []*EventParameter
	CreateTime  uint64
	Description string
	LogMessage  string
	Severity    Severity
	IpAddress   string
	DistPoller  string
	SnmpInfo    *SnmpInfo
	NodeId      uint64
	Label       string
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Uei = b.Uei
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Parameter = &b.Parameter
	x.xxx_hidden_CreateTime = b.CreateTime
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_LogMessage = b.LogMessage
	x.xxx_hidden_Severity = b.Severity
	x.xxx_hidden_IpAddress = b.IpAddress
	x.xxx_hidden_DistPoller = b.DistPoller
	x.xxx_hidden_SnmpInfo = b.SnmpInfo
	x.xxx_hidden_NodeId = b.NodeId
	x.xxx_hidden_Label = b.Label
	return m0
}

type NmsInventoryUpdateList struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InstanceId   string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3"`
	xxx_hidden_InstanceName string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3"`
	xxx_hidden_Snapshot     bool                   `protobuf:"varint,4,opt,name=snapshot,proto3"`
	xxx_hidden_Nodes        *[]*Node               `protobuf:"bytes,5,rep,name=nodes,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NmsInventoryUpdateList) Reset() {
	*x = NmsInventoryUpdateList{}
	mi := &file_spog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NmsInventoryUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NmsInventoryUpdateList) ProtoMessage() {}

func (x *NmsInventoryUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NmsInventoryUpdateList) GetInstanceId() string {
	if x != nil {
		return x.xxx_hidden_InstanceId
	}
	return ""
}

func (x *NmsInventoryUpdateList) GetInstanceName() string {
	if x != nil {
		return x.xxx_hidden_InstanceName
	}
	return ""
}

func (x *NmsInventoryUpdateList) GetSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_Snapshot
	}
	return false
}

func (x *NmsInventoryUpdateList) GetNodes() []*Node {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *NmsInventoryUpdateList) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = v
}

func (x *NmsInventoryUpdateList) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = v
}

func (x *NmsInventoryUpdateList) SetSnapshot(v bool) {
	x.xxx_hidden_Snapshot = v
}

func (x *NmsInventoryUpdateList) SetNodes(v []*Node) {
	x.xxx_hidden_Nodes = &v
}

type NmsInventoryUpdateList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InstanceId   string
	InstanceName string
	Snapshot     bool
	Nodes        []*Node
}

func (b0 NmsInventoryUpdateList_builder) Build() *NmsInventoryUpdateList {
	m0 := &NmsInventoryUpdateList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InstanceId = b.InstanceId
	x.xxx_hidden_InstanceName = b.InstanceName
	x.xxx_hidden_Snapshot = b.Snapshot
	x.xxx_hidden_Nodes = &b.Nodes
	return m0
}

type AlarmUpdateList struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InstanceId   string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3"`
	xxx_hidden_InstanceName string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3"`
	xxx_hidden_Snapshot     bool                   `protobuf:"varint,4,opt,name=snapshot,proto3"`
	xxx_hidden_Alarms       *[]*Alarm              `protobuf:"bytes,5,rep,name=alarms,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AlarmUpdateList) Reset() {
	*x = AlarmUpdateList{}
	mi := &file_spog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmUpdateList) ProtoMessage() {}

func (x *AlarmUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AlarmUpdateList) GetInstanceId() string {
	if x != nil {
		return x.xxx_hidden_InstanceId
	}
	return ""
}

func (x *AlarmUpdateList) GetInstanceName() string {
	if x != nil {
		return x.xxx_hidden_InstanceName
	}
	return ""
}

func (x *AlarmUpdateList) GetSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_Snapshot
	}
	return false
}

func (x *AlarmUpdateList) GetAlarms() []*Alarm {
	if x != nil {
		if x.xxx_hidden_Alarms != nil {
			return *x.xxx_hidden_Alarms
		}
	}
	return nil
}

func (x *AlarmUpdateList) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = v
}

func (x *AlarmUpdateList) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = v
}

func (x *AlarmUpdateList) SetSnapshot(v bool) {
	x.xxx_hidden_Snapshot = v
}

func (x *AlarmUpdateList) SetAlarms(v []*Alarm) {
	x.xxx_hidden_Alarms = &v
}

type AlarmUpdateList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InstanceId   string
	InstanceName string
	Snapshot     bool
	Alarms       []*Alarm
}

func (b0 AlarmUpdateList_builder) Build() *AlarmUpdateList {
	m0 := &AlarmUpdateList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InstanceId = b.InstanceId
	x.xxx_hidden_InstanceName = b.InstanceName
	x.xxx_hidden_Snapshot = b.Snapshot
	x.xxx_hidden_Alarms = &b.Alarms
	return m0
}

type EventUpdateList struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InstanceId   string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3"`
	xxx_hidden_InstanceName string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3"`
	xxx_hidden_Snapshot     bool                   `protobuf:"varint,4,opt,name=snapshot,proto3"`
	xxx_hidden_Event        *[]*Event              `protobuf:"bytes,5,rep,name=event,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EventUpdateList) Reset() {
	*x = EventUpdateList{}
	mi := &file_spog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateList) ProtoMessage() {}

func (x *EventUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateList) GetInstanceId() string {
	if x != nil {
		return x.xxx_hidden_InstanceId
	}
	return ""
}

func (x *EventUpdateList) GetInstanceName() string {
	if x != nil {
		return x.xxx_hidden_InstanceName
	}
	return ""
}

func (x *EventUpdateList) GetSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_Snapshot
	}
	return false
}

func (x *EventUpdateList) GetEvent() []*Event {
	if x != nil {
		if x.xxx_hidden_Event != nil {
			return *x.xxx_hidden_Event
		}
	}
	return nil
}

func (x *EventUpdateList) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = v
}

func (x *EventUpdateList) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = v
}

func (x *EventUpdateList) SetSnapshot(v bool) {
	x.xxx_hidden_Snapshot = v
}

func (x *EventUpdateList) SetEvent(v []*Event) {
	x.xxx_hidden_Event = &v
}

type EventUpdateList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InstanceId   string
	InstanceName string
	Snapshot     bool
	Event        []*Event
}

func (b0 EventUpdateList_builder) Build() *EventUpdateList {
	m0 := &EventUpdateList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InstanceId = b.InstanceId
	x.xxx_hidden_InstanceName = b.InstanceName
	x.xxx_hidden_Snapshot = b.Snapshot
	x.xxx_hidden_Event = &b.Event
	return m0
}

type MonitoringInstance struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InstanceType string                 `protobuf:"bytes,1,opt,name=instance_type,json=instanceType,proto3"`
	xxx_hidden_InstanceId   string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3"`
	xxx_hidden_InstanceName string                 `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MonitoringInstance) Reset() {
	*x = MonitoringInstance{}
	mi := &file_spog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringInstance) ProtoMessage() {}

func (x *MonitoringInstance) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MonitoringInstance) GetInstanceType() string {
	if x != nil {
		return x.xxx_hidden_InstanceType
	}
	return ""
}

func (x *MonitoringInstance) GetInstanceId() string {
	if x != nil {
		return x.xxx_hidden_InstanceId
	}
	return ""
}

func (x *MonitoringInstance) GetInstanceName() string {
	if x != nil {
		return x.xxx_hidden_InstanceName
	}
	return ""
}

func (x *MonitoringInstance) SetInstanceType(v string) {
	x.xxx_hidden_InstanceType = v
}

func (x *MonitoringInstance) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = v
}

func (x *MonitoringInstance) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = v
}

type MonitoringInstance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InstanceType string
	InstanceId   string
	InstanceName string
}

func (b0 MonitoringInstance_builder) Build() *MonitoringInstance {
	m0 := &MonitoringInstance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InstanceType = b.InstanceType
	x.xxx_hidden_InstanceId = b.InstanceId
	x.xxx_hidden_InstanceName = b.InstanceName
	return m0
}

type HeartBeat struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MonitoringInstance *MonitoringInstance    `protobuf:"bytes,1,opt,name=monitoring_instance,json=monitoringInstance,proto3"`
	xxx_hidden_Message            string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	xxx_hidden_Timestamp          uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	mi := &file_spog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_spog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HeartBeat) GetMonitoringInstance() *MonitoringInstance {
	if x != nil {
		return x.xxx_hidden_MonitoringInstance
	}
	return nil
}

func (x *HeartBeat) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *HeartBeat) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *HeartBeat) SetMonitoringInstance(v *MonitoringInstance) {
	x.xxx_hidden_MonitoringInstance = v
}

func (x *HeartBeat) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *HeartBeat) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *HeartBeat) HasMonitoringInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MonitoringInstance != nil
}

func (x *HeartBeat) ClearMonitoringInstance() {
	x.xxx_hidden_MonitoringInstance = nil
}

type HeartBeat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MonitoringInstance *MonitoringInstance
	Message            string
	Timestamp          uint64
}

func (b0 HeartBeat_builder) Build() *HeartBeat {
	m0 := &HeartBeat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MonitoringInstance = b.MonitoringInstance
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

var File_spog_proto protoreflect.FileDescriptor

const file_spog_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spog.proto\x12\"org.opennms.plugin.grpc.proto.spog\x1a\x1bgoogle/protobuf/empty.proto\"\x9f\x01\n" +
	"\fNodeCriteria\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0eforeign_source\x18\x02 \x01(\tR\rforeignSource\x12\x1d\n" +
	"\n" +
	"foreign_id\x18\x03 \x01(\tR\tforeignId\x12\x1d\n" +
	"\n" +
	"node_label\x18\x04 \x01(\tR\tnodeLabel\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"y\n" +
	"\vIpInterface\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12!\n" +
	"\fprimary_type\x18\x03 \x01(\tR\vprimaryType\x12\x18\n" +
	"\aservice\x18\x04 \x03(\tR\aservice\"\xb3\x02\n" +
	"\rSnmpInterface\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bif_index\x18\x02 \x01(\rR\aifIndex\x12\x19\n" +
	"\bif_descr\x18\x03 \x01(\tR\aifDescr\x12\x17\n" +
	"\aif_type\x18\x04 \x01(\rR\x06ifType\x12\x17\n" +
	"\aif_name\x18\x05 \x01(\tR\x06ifName\x12\x19\n" +
	"\bif_speed\x18\x06 \x01(\x04R\aifSpeed\x12&\n" +
	"\x0fif_phys_address\x18\a \x01(\tR\rifPhysAddress\x12&\n" +
	"\x0fif_admin_status\x18\b \x01(\rR\rifAdminStatus\x12$\n" +
	"\x0eif_oper_status\x18\t \x01(\rR\fifOperStatus\x12\x19\n" +
	"\bif_alias\x18\n" +
	" \x01(\tR\aifAlias\"\x82\x04\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0eforeign_source\x18\x02 \x01(\tR\rforeignSource\x12\x1d\n" +
	"\n" +
	"foreign_id\x18\x03 \x01(\tR\tforeignId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1a\n" +
	"\bcategory\x18\x05 \x03(\tR\bcategory\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vsys_contact\x18\b \x01(\tR\n" +
	"sysContact\x12'\n" +
	"\x0fsys_description\x18\t \x01(\tR\x0esysDescription\x12\"\n" +
	"\rsys_object_id\x18\n" +
	" \x01(\tR\vsysObjectId\x12\x19\n" +
	"\bsys_name\x18\v \x01(\tR\asysName\x12R\n" +
	"\fip_interface\x18\f \x03(\v2/.org.opennms.plugin.grpc.proto.spog.IpInterfaceR\vipInterface\x12X\n" +
	"\x0esnmp_interface\x18\r \x03(\v21.org.opennms.plugin.grpc.proto.spog.SnmpInterfaceR\rsnmpInterface\"\x8c\a\n" +
	"\x05Alarm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uei\x18\x02 \x01(\tR\x03uei\x12U\n" +
	"\rnode_criteria\x18\x03 \x01(\v20.org.opennms.plugin.grpc.proto.spog.NodeCriteriaR\fnodeCriteria\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12#\n" +
	"\rreduction_key\x18\x06 \x01(\tR\freductionKey\x12\x12\n" +
	"\x04type\x18\a \x01(\rR\x04type\x12\x14\n" +
	"\x05count\x18\b \x01(\x04R\x05count\x12\x1a\n" +
	"\bseverity\x18\t \x01(\rR\bseverity\x12(\n" +
	"\x10first_event_time\x18\n" +
	" \x01(\x04R\x0efirstEventTime\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x1f\n" +
	"\vlog_message\x18\f \x01(\tR\n" +
	"logMessage\x12\x19\n" +
	"\back_user\x18\r \x01(\tR\aackUser\x12\x19\n" +
	"\back_time\x18\x0e \x01(\x04R\aackTime\x12&\n" +
	"\x0flast_event_time\x18\x10 \x01(\x04R\rlastEventTime\x12\x19\n" +
	"\bif_index\x18\x11 \x01(\rR\aifIndex\x123\n" +
	"\x15operator_instructions\x18\x12 \x01(\tR\x14operatorInstructions\x12\x1b\n" +
	"\tclear_key\x18\x13 \x01(\tR\bclearKey\x126\n" +
	"\x17managed_object_instance\x18\x14 \x01(\tR\x15managedObjectInstance\x12.\n" +
	"\x13managed_object_type\x18\x15 \x01(\tR\x11managedObjectType\x12M\n" +
	"\frelatedAlarm\x18\x16 \x03(\v2).org.opennms.plugin.grpc.proto.spog.AlarmR\frelatedAlarm\x12(\n" +
	"\x10last_update_time\x18\x19 \x01(\x04R\x0elastUpdateTime\"D\n" +
	"\x04Type\x12\x16\n" +
	"\x12PROBLEM_WITH_CLEAR\x10\x00\x12\t\n" +
	"\x05CLEAR\x10\x01\x12\x19\n" +
	"\x15PROBLEM_WITHOUT_CLEAR\x10\x02\"N\n" +
	"\x0eEventParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xa3\x01\n" +
	"\bSnmpInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bspecific\x18\x03 \x01(\rR\bspecific\x12\x18\n" +
	"\ageneric\x18\x04 \x01(\rR\ageneric\x12\x1c\n" +
	"\tcommunity\x18\x05 \x01(\tR\tcommunity\x12\x19\n" +
	"\btrap_oid\x18\x06 \x01(\tR\atrapOid\"\x8e\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uei\x18\x02 \x01(\tR\x03uei\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x04R\x04time\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12P\n" +
	"\tparameter\x18\x05 \x03(\v22.org.opennms.plugin.grpc.proto.spog.EventParameterR\tparameter\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x04R\n" +
	"createTime\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1f\n" +
	"\vlog_message\x18\b \x01(\tR\n" +
	"logMessage\x12H\n" +
	"\bseverity\x18\t \x01(\x0e2,.org.opennms.plugin.grpc.proto.spog.SeverityR\bseverity\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x1f\n" +
	"\vdist_poller\x18\v \x01(\tR\n" +
	"distPoller\x12H\n" +
	"\bsnmpInfo\x18\f \x01(\v2,.org.opennms.plugin.grpc.proto.spog.SnmpInfoR\bsnmpInfo\x12\x17\n" +
	"\anode_id\x18\r \x01(\x04R\x06nodeId\x12\x14\n" +
	"\x05label\x18\x0e \x01(\tR\x05label\"\xba\x01\n" +
	"\x16NmsInventoryUpdateList\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\x12>\n" +
	"\x05nodes\x18\x05 \x03(\v2(.org.opennms.plugin.grpc.proto.spog.NodeR\x05nodes\"\xb6\x01\n" +
	"\x0fAlarmUpdateList\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\x12A\n" +
	"\x06alarms\x18\x05 \x03(\v2).org.opennms.plugin.grpc.proto.spog.AlarmR\x06alarms\"\xb4\x01\n" +
	"\x0fEventUpdateList\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\x12?\n" +
	"\x05event\x18\x05 \x03(\v2).org.opennms.plugin.grpc.proto.spog.EventR\x05event\"\x7f\n" +
	"\x12MonitoringInstance\x12#\n" +
	"\rinstance_type\x18\x01 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\"\xac\x01\n" +
	"\tHeartBeat\x12g\n" +
	"\x13monitoring_instance\x18\x01 \x01(\v26.org.opennms.plugin.grpc.proto.spog.MonitoringInstanceR\x12monitoringInstance\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp*g\n" +
	"\bSeverity\x12\x11\n" +
	"\rINDETERMINATE\x10\x00\x12\v\n" +
	"\aCLEARED\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\t\n" +
	"\x05MINOR\x10\x04\x12\t\n" +
	"\x05MAJOR\x10\x05\x12\f\n" +
	"\bCRITICAL\x10\x062\xaa\x03\n" +
	"\x17NmsInventoryServiceSync\x12k\n" +
	"\x0fInventoryUpdate\x12:.org.opennms.plugin.grpc.proto.spog.NmsInventoryUpdateList\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01\x12`\n" +
	"\vAlarmUpdate\x123.org.opennms.plugin.grpc.proto.spog.AlarmUpdateList\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01\x12`\n" +
	"\vEventUpdate\x123.org.opennms.plugin.grpc.proto.spog.EventUpdateList\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01\x12^\n" +
	"\x0fHeartBeatUpdate\x12-.org.opennms.plugin.grpc.proto.spog.HeartBeat\x1a\x16.google.protobuf.Empty\"\x00(\x010\x01B&\n" +
	"\"org.opennms.plugin.grpc.proto.spogP\x01b\x06proto3"

var file_spog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spog_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_spog_proto_goTypes = []any{
	(Severity)(0),                  // 0: org.opennms.plugin.grpc.proto.spog.Severity
	(Alarm_Type)(0),                // 1: org.opennms.plugin.grpc.proto.spog.Alarm.Type
	(*NodeCriteria)(nil),           // 2: org.opennms.plugin.grpc.proto.spog.NodeCriteria
	(*IpInterface)(nil),            // 3: org.opennms.plugin.grpc.proto.spog.IpInterface
	(*SnmpInterface)(nil),          // 4: org.opennms.plugin.grpc.proto.spog.SnmpInterface
	(*Node)(nil),                   // 5: org.opennms.plugin.grpc.proto.spog.Node
	(*Alarm)(nil),                  // 6: org.opennms.plugin.grpc.proto.spog.Alarm
	(*EventParameter)(nil),         // 7: org.opennms.plugin.grpc.proto.spog.EventParameter
	(*SnmpInfo)(nil),               // 8: org.opennms.plugin.grpc.proto.spog.SnmpInfo
	(*Event)(nil),                  // 9: org.opennms.plugin.grpc.proto.spog.Event
	(*NmsInventoryUpdateList)(nil), // 10: org.opennms.plugin.grpc.proto.spog.NmsInventoryUpdateList
	(*AlarmUpdateList)(nil),        // 11: org.opennms.plugin.grpc.proto.spog.AlarmUpdateList
	(*EventUpdateList)(nil),        // 12: org.opennms.plugin.grpc.proto.spog.EventUpdateList
	(*MonitoringInstance)(nil),     // 13: org.opennms.plugin.grpc.proto.spog.MonitoringInstance
	(*HeartBeat)(nil),              // 14: org.opennms.plugin.grpc.proto.spog.HeartBeat
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_spog_proto_depIdxs = []int32{
	3,  // 0: org.opennms.plugin.grpc.proto.spog.Node.ip_interface:type_name -> org.opennms.plugin.grpc.proto.spog.IpInterface
	4,  // 1: org.opennms.plugin.grpc.proto.spog.Node.snmp_interface:type_name -> org.opennms.plugin.grpc.proto.spog.SnmpInterface
	2,  // 2: org.opennms.plugin.grpc.proto.spog.Alarm.node_criteria:type_name -> org.opennms.plugin.grpc.proto.spog.NodeCriteria
	6,  // 3: org.opennms.plugin.grpc.proto.spog.Alarm.relatedAlarm:type_name -> org.opennms.plugin.grpc.proto.spog.Alarm
	7,  // 4: org.opennms.plugin.grpc.proto.spog.Event.parameter:type_name -> org.opennms.plugin.grpc.proto.spog.EventParameter
	0,  // 5: org.opennms.plugin.grpc.proto.spog.Event.severity:type_name -> org.opennms.plugin.grpc.proto.spog.Severity
	8,  // 6: org.opennms.plugin.grpc.proto.spog.Event.snmpInfo:type_name -> org.opennms.plugin.grpc.proto.spog.SnmpInfo
	5,  // 7: org.opennms.plugin.grpc.proto.spog.NmsInventoryUpdateList.nodes:type_name -> org.opennms.plugin.grpc.proto.spog.Node
	6,  // 8: org.opennms.plugin.grpc.proto.spog.AlarmUpdateList.alarms:type_name -> org.opennms.plugin.grpc.proto.spog.Alarm
	9,  // 9: org.opennms.plugin.grpc.proto.spog.EventUpdateList.event:type_name -> org.opennms.plugin.grpc.proto.spog.Event
	13, // 10: org.opennms.plugin.grpc.proto.spog.HeartBeat.monitoring_instance:type_name -> org.opennms.plugin.grpc.proto.spog.MonitoringInstance
	10, // 11: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.InventoryUpdate:input_type -> org.opennms.plugin.grpc.proto.spog.NmsInventoryUpdateList
	11, // 12: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.AlarmUpdate:input_type -> org.opennms.plugin.grpc.proto.spog.AlarmUpdateList
	12, // 13: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.EventUpdate:input_type -> org.opennms.plugin.grpc.proto.spog.EventUpdateList
	14, // 14: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.HeartBeatUpdate:input_type -> org.opennms.plugin.grpc.proto.spog.HeartBeat
	15, // 15: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.InventoryUpdate:output_type -> google.protobuf.Empty
	15, // 16: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.AlarmUpdate:output_type -> google.protobuf.Empty
	15, // 17: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.EventUpdate:output_type -> google.protobuf.Empty
	15, // 18: org.opennms.plugin.grpc.proto.spog.NmsInventoryServiceSync.HeartBeatUpdate:output_type -> google.protobuf.Empty
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_spog_proto_init() }
func file_spog_proto_init() {
	if File_spog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spog_proto_rawDesc), len(file_spog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spog_proto_goTypes,
		DependencyIndexes: file_spog_proto_depIdxs,
		EnumInfos:         file_spog_proto_enumTypes,
		MessageInfos:      file_spog_proto_msgTypes,
	}.Build()
	File_spog_proto = out.File
	file_spog_proto_goTypes = nil
	file_spog_proto_depIdxs = nil
}
